feat:データの保存失敗時、エラー文を出力する処理を追加

diff --git a/password_manager b/password_manager
--- a/password_manager
+++ b/password_manager
@@ -33,7 +33,13 @@ done
 
 if [ -z "$error_messages" ]; then
     # エラーが無い場合、ファイルにリダイレクトして、感謝文を出力
-    echo "${user_inputs[0]}":"${user_inputs[1]}":"${user_inputs[2]}" >> user_inputs
+    (echo "${user_inputs[0]}":"${user_inputs[1]}":"${user_inputs[2]}" >> d/user_inputs) 2>> error.txt
+
+    if [ $? -ne 0 ]; then
+        printf '\033[31m入力内容の保存に失敗しました\033[0m\n'
+        return
+    fi
+
     echo -e "Thank you\033[31m!\033[0m"
 else
     # エラーがある場合、配列のエラー文を出力
